### ISSUE TITLE
Module is not working

### ISSUE THREAD

**Issue by wjglerum** [dirkjonker/ansible-dcos#1]
We installed this module into `/usr/share/ansible/plugin/modules` and it seems to load fine. It was complaining about a missing interpreter so we added a shebang line with Python to each file. However it still doesn't seem to work. It fails every time with the error below and nothing happens, we get the same result for different actions:
```
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "module_stderr": "", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 0
}
```
Tried executing one of the actions manually with Python and we get the same behaviour, nothing happens and Python exists normally.

**Environment**
```
# ansible-playbook --version
ansible-playbook 2.5.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible-playbook
  python version = 2.7.5 (default, Apr 11 2018, 07:36:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```
```
DC/OS version: 1.10.5 and 1.11.0
dcos-python version: 0.1.3
```
CC: @jdijt

**Comment by dirkjonker** [comment]
Hi @wjglerum good to see you tested this! Sorry to hear it doesn't work.
Can you try putting the action_plugins in the root folder where you run the playbook from? I did not test it in /usr/share/...

Alternatively you might try the module in dcos-labs; https://github.com/dcos-labs/ansible-dcos-module/
